### ISSUE TITLE
Return value is different when using tqdm

### ISSUE THREAD

**Issue by survili** [powerpak/tqdm-ruby#1]
Hi, love this little gem, it's very useful. 

Below is a little sample, where you can see that a return value is different when using tqdm.

[6] pry(main)> (0...1000).tqdm.each {|x| sleep 0.001 }
=> 1
[7] pry(main)> (0...1000).each {|x| sleep 0.001 }
=> 0...1000

Thank you

**Comment by powerpak** [comment]
Thanks for pointing this out! @chadmetcalf was kind in fixing it.

Fixed by ca375d86bf05fe8389df77b7cfcb48b0e12a64fa
